export const LABELS = Object.freeze({
    WELCOME_MESSAGE: 'Welcome to My Application',
    LOGIN: 'Log In',
    SIGNUP_BUTTON: 'Sign Up',
    REGISTER_HEADING: 'Join Saferly!',
    REGISTER_SUBHEADING: 'Create your account',
    NAME_LABEL: 'Name',
    EMAIL_LABEL: 'Email',
    PASSWORD_LABEL: 'Password',
    CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    REGISTER_BUTTON: 'Register',
    ALREADY_HAVE_ACCOUNT: "Already have an account?",
    LOGIN_LINK: 'Log In',
    SIGN_IN:"Sign In",
    FORGET_PASSWORD:"Forgot password ?",
    DONT_HAVE_A_ACCOUNT:"Don't have an account?",
    LOGIN_TEXT_CREATE_ACCOUNT:"Create Account",
    LOGIN_TEXT_CAROUSEL_TITLE_1:"Smooth Snowflake to BigQuery Migration",
    LOGIN_TEXT_CAROUSEL_TITLE_2:"Optimized Performance with BigQuery",
    LOGIN_TEXT_CAROUSEL_TITLE_3:"Advanced AI and ML Capabilities",
    LOGIN_TEXT_CAROUSEL_DESCRIPTION_1:"Easily migrate your data from Snowflake to BigQuery with minimal downtime. Our automated pipelines ensure data integrity and consistency, allowing for a smooth transition to Google's cloud ecosystem.",
    LOGIN_TEXT_CAROUSEL_DESCRIPTION_2:"Take advantage of BigQuery’s serverless architecture to run high-speed SQL queries on massive datasets. Reduce costs and improve analytics efficiency with pay-as-you-go pricing.",
    LOGIN_TEXT_CAROUSEL_DESCRIPTION_3:"Unlock powerful AI and machine learning features in BigQuery, including built-in support for predictive analytics. Leverage BigQuery ML to run models directly on your data without moving it.",
    ACCOUNT_TEXT_ACCOUNT_LEVEL_CONFIGURATION:"Account Level Configuration",
    ACCOUNT_TEXT_SUB_HEADING:"Please enter your Snowflake and BigQuery account details to start the data migration process.",
    ACCOUNT_TEXT_SNOWFLAKE_ACCOUNT:"Snowflake Account",
    ACCOUNT_TEXT_BIGQUERY_PROJECT:"BigQuery Project",
    ACCOUNT_TEXT_VERSION:"Version",
    ACCOUNT_TEXT_WAREHOUSE_NAME:"Warehouse Name",
    ACCOUNT_TEXT_SIZE: "Size",
    ACCOUNT_TEXT_MIN_CLUSTER_COUNT: "Min Cluster Count",
    ACCOUNT_TEXT_MAX_CLUSTER_COUNT: "Max Cluster Count",
    ACCOUNT_TEXT_TYPE: "Type",
    ACCOUNT_TEXT_SCALING_POLICY: "Scaling Policy",
    ACCOUNT_TEXT_TOTAL_CREDITS_LAST_90_DAYS: "Total Credits Last 90 Days",
    ACCOUNT_TEXT_AVERAGE_DAILY_CREDITS: "Average Daily Credits",
    ACCOUNT_TEXT_CREATED_DATETIME: "Created Datetime"
  });
  